### ISSUE TITLE
Contribute to participate in HacktoberFest 2020

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#1]
Feel free to add everything you want from blogs to codes to even show off your projects!

Happy Coding!!!

**Comment by shin-iji** [comment]
@its-harshil can i do this?

**Comment by harshilp24** [comment]
Yes you can

**Comment by kartikeytyagi15** [comment]
Added code to Java folder

**Comment by Mahnoor123-Fatima** [comment]
i want to work on it

**Comment by mk1107** [comment]
I can add Fibonacci Search and Bubble sort  in cpp folder.
Please allow me to work on this task.

**Comment by mk1107** [comment]
I have made PR please accept it.
https://github.com/its-harshil/Hacktoberfest_2020/pull/44#issue-497054386

**Comment by cyberdev25** [comment]
I want to work on this issue.

**Comment by cyberdev25** [comment]
I have made my PR . Please have a look at it.

**Comment by KUndn** [comment]
i have made my PR #64 .
please have a look at it.
