### ISSUE TITLE
Contribute to participate in HacktoberFest 2021 #1

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#225]
It's Day 1 of Hacktober Fest 2021, So we have decided to add some projects. So make any of below listed program in any language you want.

1). Desktop Notifier App (DONE)
2). Website Blocker (DONE)
3). Rock, Paper, Scissors (DONE)
4).  ̶C̶̶̶a̶̶̶l̶̶̶c̶̶̶u̶̶̶l̶̶̶a̶̶̶t̶̶̶o̶̶̶r̶̶̶ (DONE)

If you have any other idea please comment below, Happy coding !!

Feel free to add everything you want from blogs to codes to even show off your projects!
Make sure you follow the guidelines !

Happy Coding!!!

> working on calculator! pls assign task to me

**Comment by kvnal** [comment]
working on calculator! pls assign task to me

**Comment by harshilp24** [comment]
@kvnal you can start working, pls mention the language.

**Comment by UVid489** [comment]
Can I work on rock paper scissors? I will use python. Please assign this task to me .

**Comment by Ayushchaudhary-Github** [comment]
I can make calculator using python can you assign me?

**Comment by Naman-pokhriyal** [comment]
Can I make a tic-tack-toe game using python?

**Comment by harshilp24** [comment]
@vidnyani you can start working !

**Comment by harshilp24** [comment]
@YushChaudhary calculator is already taken, you can view new projects list tomorrow or suggest some :)

**Comment by harshilp24** [comment]
@Naman-pokhriyal it is already done, you can update the code(https://github.com/its-harshil/Hacktoberfest_2021/tree/main/TIC%20TAC%20TOE%20USING%20PYTHON) or wait for new project list or suggest some new idea :)

**Comment by Ayushchaudhary-Github** [comment]
ok thanks

**Comment by UVid489** [comment]
> @vidnyani you can start working !

On it! Thanks.

**Comment by anirudhgray** [comment]
Hey! Can I work on the rock paper scissors?

**Comment by Meowyam** [comment]
I'll do rock paper scissors in prolog!

**Comment by kvnal** [comment]
> @kvnal you can start working, pls mention the language.

Cpp advance calculator added! pls review the changes. #249 👈
Thanks!🤟

**Comment by Debalay-dasgupta** [comment]
@its-harshil  pls assign Desktop notifier app task to me.It will be in python

**Comment by itsPriyanshuRaj** [comment]
Hey @its-harshil I see projects in the list are either already completed or someone is here to complete the project before me. So i was wondering if I can suggest some new projects to work on.

**Comment by harshilp24** [comment]
@itsPriyanshuRaj sure can suggest your ideas, no issues !

**Comment by harshilp24** [comment]
@Debalay-dasgupta yes you can work on !!

**Comment by Meowyam** [comment]
> I'll do rock paper scissors in prolog!

I made a pull request for rock paper scissors in prolog. :)

**Comment by itsPriyanshuRaj** [comment]
> @itsPriyanshuRaj sure can suggest your ideas, no issues !

Here are some suggestions:
Digital Clock , Color Game , Text Editor (like Notepad) , Image Converter 

These are few good first use or you can say first timers only projects that I would love to recommend. Let me know if you like anyone of these and if  I can contribute to any of these.

**Comment by harshilp24** [comment]
@itsPriyanshuRaj you start by any of the above suggestions !! If You want you can even submit all 4 of them, no issue.

**Comment by Gaurav18-2001** [comment]
pls assign web blocker to me. it will be in python

**Comment by harshilp24** [comment]
> pls assign web blocker to me. it will be in python

sure go ahead !

**Comment by Debalay-dasgupta** [comment]
@its-harshil  I am done with the Desktop-notifier .Thank you for the opportunity ,kindly merge my PR .

**Comment by itsPriyanshuRaj** [comment]
> @itsPriyanshuRaj you start by any of the above suggestions !! If You want you can even submit all 4 of them, no issue.

I will love to start from Digital Clock ,will make the PR request soon.
