### ISSUE TITLE
Contribute to participate in HacktoberFest 2021 #2

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#241]
It's Day 2 of Hacktober Fest 2021, So we have decided to add some projects. So make any of below listed program in any language you want.

1). A File Converter (DONE)
2). A Quiz App (DONE)
3). To-do List (DONE)

If you have any other idea please comment below, Happy coding !!

Feel free to add everything you want from blogs to codes to even show off your projects!
Make sure you follow the guidelines !

Happy Coding!!!

**Comment by Niyati3031** [comment]
can you assign me this please @its-harshil its my first time contributing please...

**Comment by harshilp24** [comment]
@Niyati3031 choose one topic and you can start working !!

**Comment by SO1ee** [comment]
Please assign me To-do-list

**Comment by harshilp24** [comment]
@SO1ee you can start working.

**Comment by YOGENDERSS** [comment]
A File Converter-- i m working on it.

**Comment by FlyingwithCaptainSoumya** [comment]
@its-harshil I want to work on the quiz app

**Comment by harshilp24** [comment]
@FlyingwithCaptainSoumya go ahead !

**Comment by HVbajoria** [comment]
Hello @its-harshil  I have made a quiz application to solve today's task. 
I have made a pull request for the same can you please check out. 
Thank you.

**Comment by gauravs1303** [comment]
Can I create a python code for chat server.

**Comment by harshilp24** [comment]
@gauravs1303 sure!

**Comment by gauravs1303** [comment]
> @gauravs1303 sure!

I have created a pr but you haven't accepted it yet
