### ISSUE TITLE
Repo is Excluded from HacktoberFest

### ISSUE THREAD

**Issue by noel-johnson** [its-harshil/Hacktoberfest_2020#288]

**Comment by harshilp24** [comment]
@noel-johnson can you provide details for the same ?

**Comment by noel-johnson** [comment]
Sure, I just submitted a PR for issue #279. Went to the [Hacktocber](https://hacktoberfest.digitalocean.com/profile) dashboard for checking it out. It says the project is excluded. 
![image](https://user-images.githubusercontent.com/42847827/136030485-056170a7-9546-4873-9d0c-bcdb27863b6c.png)

**Comment by harshilp24** [comment]
@noel-johnson thanks, I'll check with others and If it is excluded, I'll archive the repo !!

**Comment by dhananjay8968** [comment]
Why this project is excluded @its-harshil ?
