### ISSUE TITLE
Want to Contribute and participate in Hacktober Fest 2020

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#3]
Checkout the existing issues or open new one and ask for assigning the issue. Now you are good to go.
Happy Coding!!!

**Comment by shubhangi-singh21** [comment]
@its-harshil what type of C++ and Data Structures contributions are you looking for?

**Comment by GantaChaitra** [comment]
Hey @its-harshil ... i want to contribute for this repository ... can u assign me any?

**Comment by harshilp24** [comment]
@GantaChaitra you can work on any project you want
