### ISSUE TITLE
Day 3 HacktoberFest -  Extract Text from Image

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#52]
It's Day 3 of Hacktober Fest 2020, So we have decided to add some challenging works. So make a program where you can  Extract Text from Image you can use any language, library you want. Don't forget to update contributors file. You can also add your issues or challenges here.

We will add more challenges soon, Happy Coding !!

**Comment by AnshMishra2001** [comment]
I want to work on this issue

**Comment by harshilp24** [comment]
@AnshMishra2001 Sure. Go ahead. Happy Coding!!

**Comment by tdserapio** [comment]
I would also want to work on this issue

**Comment by Nikzy7** [comment]
Hey There ! Check out my PR #53 . Happy Hacktoberfest !!!!!
