### ISSUE TITLE
Day 3 HacktoberFest - Create Program 

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#54]
It's Day 3 of Hacktober Fest 2020, So we have decided to add some challenging works. So make any of below listed program in any language you want.

1) Text to Speech
2) Language Translator
3) Playing with PDFs (Adding watermarks, converting PDF into text etc)

We will add more challenges soon, Happy Coding !!

**Comment by aditya1abhinav** [comment]
Assign me for this. I can create programs in C, C++, Java and Python

**Comment by jigar-sable** [comment]
Assign me for creating Text to Speech in Pyhton.

**Comment by harshilp24** [comment]
@aditya1abhinav sure go ahead and comment which programs are you adding and in which language.

**Comment by harshilp24** [comment]
> Assign me for creating Text to Speech in Pyhton.

Okay go ahead , happy coding !!

**Comment by Nikzy7** [comment]
Hey ! Check my PR #56 . The TTS is offline !

**Comment by aditya1abhinav** [comment]
@itsharshil I'll write in Java and Python. Some DS-Algo programs.

**Comment by harshilp24** [comment]
@aditya1abhinav okay go ahead

**Comment by aditya1abhinav** [comment]
Check #59 @itsharshil , thank you

**Comment by Nikzy7** [comment]
Hey @its-harshil can you shed some light on what kind of I/O format you want for the translator. I can do it in python. What i thought of doing is, get user input -> ask for target language from a menu -> translate.

**Comment by ShashankAgarwal77** [comment]
Hello, @its-harshil is it okay if I created the "text-to-speech" work in JavaScript?

**Comment by harshilp24** [comment]
@ShashankAgarwal77 yes

**Comment by harshilp24** [comment]
> Hey @its-harshil can you shed some light on what kind of I/O format you want for the translator. I can do it in python. What i thought of doing is, get user input -> ask for target language from a menu -> translate.

Nice, for now you can use English Hindi

**Comment by ShashankAgarwal77** [comment]
okay, then I will push the code as soon as possible.

**Comment by cBridges851** [comment]
I'd like to have a go at implementing text-to-speech in Python!

**Comment by aditya1abhinav** [comment]
#59 check it and please merge it @its-harshil

**Comment by jaskarans2000** [comment]
Can I work on text to speech in java?

**Comment by manishgautam30** [comment]
I have implemented text to speech in python please have a look. 
Its there in your pull request to get merged👍

**Comment by amith-gowda** [comment]
Hey, I can try to build the PDF app in Java

**Comment by cBridges851** [comment]
I've created a pull request for a text to speech python program, I would appreciate any feedback! I really enjoyed making this program!
According to my Hacktoberfest profile, this is apparently an "Ineligible Repository" for some reason? I think it could possibly be the capitalisation of the "Hacktoberfest" label on this repo, I think it might have to be all lowercase? Thank you!
![image](https://user-images.githubusercontent.com/54030147/94994105-7ec06e00-058d-11eb-86e7-fb3469922978.png)
![image](https://user-images.githubusercontent.com/54030147/94994137-add6df80-058d-11eb-9f38-b79af0af1c06.png)

**Comment by allegium** [comment]
Hi!
I don't know where I can ask some questions, so sorry if I've chosen the wrong place to ask.
I'm new to all this stuff, so could somebody tell me how could I delete a file from commit? 
And also how long does the process of merging takes?
Thank you so much!😇

**Comment by harshilp24** [comment]
@cBridges851  hey thank you to let us know about the issue

**Comment by cBridges851** [comment]
Hiya, the Hacktoberfest dashboard still shows "ineligible repository", so I'm still not sure if it is the right label. The only difference I can notice is the background colour of the labels - the ones with the purple background seem to be the ones that relate to Hacktoberfest. 
![image](https://user-images.githubusercontent.com/54030147/95017549-d58f7b80-0651-11eb-855e-cc67abe6f3fa.png)

**Comment by harshilp24** [comment]
> Hiya, the Hacktoberfest dashboard still shows "ineligible repository", so I'm still not sure if it is the right label. The only difference I can notice is the background colour of the labels - the ones with the purple background seem to be the ones that relate to Hacktoberfest.
> ![image](https://user-images.githubusercontent.com/54030147/95017549-d58f7b80-0651-11eb-855e-cc67abe6f3fa.png)

Hii the issue is solved, please check on your hacktober fest profile and let us know

**Comment by cBridges851** [comment]
The issue shows up as being in the review period now, thanks for fixing 😄

**Comment by gracyashhh** [comment]
Hey, I want to work on Language Translator, Can you assign me that?

**Comment by ShashankAgarwal77** [comment]
Hey, @its-harshil I just PR the Text to Speech Web-App. But Hacktoberfest dashboard shows this

Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it.

Please solve this issue and merge the PR.

**Comment by ShashankAgarwal77** [comment]
@its-harshil please review the project and accept the PR 👍

**Comment by ArpitaGanatra** [comment]
Can I go ahead with playing with pdfs? I can write a code for that in Python.
