### ISSUE TITLE
Add Set Operations in Java and Python languages

### ISSUE THREAD

**Issue by bhavyakjain** [its-harshil/Hacktoberfest_2020#71]
Add the following Set Operations in Java and Python languages:
- Union
- Intersection
- Difference
- Symmetric Difference

**Comment by SaiSrichandra** [comment]
Hey @bhavyakjain I would love to work on this
Can you assign it to me

**Comment by Nikzy7** [comment]
Hey @its-harshil check out my PR #72 for this issue. It'd be really great if you could add the label hacktoberfest-accepted, or hacktoberfest to this issue.

**Comment by bhavyakjain** [comment]
I have created PR#74 for this issue. Please add "Hacktoberfest" label for this issue and merge it.
