### ISSUE TITLE
Day 5 Hacktober fest - Create Program

### ISSUE THREAD

**Issue by harshilp24** [its-harshil/Hacktoberfest_2020#80]
It's Day 5 of Hacktober Fest 2020, So we have decided to add some challenging works. So make any of below listed program in any language you want.

1). Hand Gestures Detection
2). Simple Web App that calculates BMI
3). URL Shortener
4). Speed Typing Test
5). Tic Tac Toe

We will add more challenges soon, Happy Coding !!

**Comment by tdserapio** [comment]
May I contribute to Number 2? I would really appreciate it.

**Comment by harshilp24** [comment]
> May I contribute to Number 2? I would really appreciate it.

Sure go ahead, happy coding !!

**Comment by dhiganthrao** [comment]
Is it fine if I work on Number 3? Seems like an interesting project.

**Comment by harshilp24** [comment]
> Is it fine if I work on Number 3? Seems like an interesting project.

Yes sure

**Comment by Hinal-Srivastava** [comment]
I'll contribute 5 in Python👍

**Comment by harshitgupta2000** [comment]
I want to add sorting program in python please assign it to me.

**Comment by dhiganthrao** [comment]
@its-harshil Whenever you have the time, kindly review my pull request and merge it if you see fit. Thanks again!

**Comment by cyberdev25** [comment]
hey @its-harshil , I want to  contribute to speed typing test . Could you assign it to me?

**Comment by harshilp24** [comment]
> hey @its-harshil , I want to contribute to speed typing test . Could you assign it to me?

Sure go ahead

**Comment by GauravKhulway** [comment]
May I contribute to Number 5(in C++)? I would really appreciate it.

**Comment by harshilp24** [comment]
> May I contribute to Number 5(in C++)? I would really appreciate it.

Sure go ahead, happy coding !!

**Comment by Soundug** [comment]
Hi there! Has anyone taken up number 1?

**Comment by harshilp24** [comment]
> Hi there! Has anyone taken up number 1?

Nope, go for it

**Comment by AasthaGoyalgit** [comment]
May I contribute to 3?

**Comment by Purvi9399** [comment]
Can I contribute to 5 in Python or java? Please assign it to me.

**Comment by Hinal-Srivastava** [comment]
> Can I contribute to 5 in Python or java? Please assign it to me.

I'm working on it in Python. You can continue in Java, 😊

**Comment by AasthaGoyalgit** [comment]
Ok I'll work on this in java👍

**Comment by Purvi9399** [comment]
> > Can I contribute to 5 in Python or java? Please assign it to me.
> 
> I'm working on it in Python. You can continue in Java, blush

Okay cool, I'll be working on JAVA tic_tac_toe.

**Comment by SHIVANI0708** [comment]
i would like to contribute to number  5 in c++

**Comment by cyberdev25** [comment]
hey @its-harshil , I have made my pr #119  to the issue assigned to me. Kindly have a look at it.

**Comment by shashwatbangar** [comment]
hello @its-harshil can i work on second one ?

**Comment by SanyaNanda** [comment]
hey, i would like to work on the url shortener

**Comment by sentiww** [comment]
I'll take 4 in C# unless someone is already doing that

**Comment by harshilp24** [comment]
@SentiWW sure go ahead

**Comment by ShashankAgarwal77** [comment]
Hey, @its-harshil thanks for creating daily challenges...I would like to contribute another web-app project as Online BMI Calculator. I send you PR..please review it and approve it. Thanks in Advance :)

**Comment by Gopal-Dahale** [comment]
can anybody contribute or you will assign the tasks.

**Comment by harshilp24** [comment]
@Gopal-Dahale anyone can contribute

**Comment by SaiSudhaV** [comment]
Hey, @its-harshil. I have sent PR of tic tac toe game in python. Please review it and I hope you approve it and merge. Thanks in Advance
